summary = readRDS("summarySCC_PM25.rds")
source = readRDS("Source_Classification_Code.rds")
summary_balt = subset(summary,fips=="24510")
te = tapply(summary_balt$Emissions,summary_balt$year,sum)
years = unique(summary$year)
plot(years,te,xlab = "Year",ylab = "Total PM Emissions in Baltimore",pch = 19,type = "l",col = "red")
title("Total PM Emission in Baltimore")
dev.copy(png,"plot2.png")
dev.off()
